[project]
name = "ref"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "lxml[html-clean]>=5.3.2",
    "markdownify>=1.1.0",
    "readability-lxml>=0.8.1",
]
